version: '2'
services:
  web:
    restart: always
    build:
     context: .
     dockerfile: Dockerfile
    container_name: timesheetapp
    environment:
     - NODE_ENV=production
     - DB_1_PORT_27017_TCP_ADDR=db
    depends_on:
     - db
    ports:
     - "1313:80"
  nginx:
    restart: always
    build:
     context: .
     dockerfile: Dockerfile-nginx
    container_name: nginx-container
    ports:
     - "80:80"
     - "443:443"
    depends_on:
     - web
  db:
    image: mongo:3.2
    ports:
     - "27017:27017"
    restart: always
    volumes_from:
      - db-data
  db-data:
    image: mongo:3.2
    volumes:
      - /data/db
      - /var/lib/mongodb
      - /var/log/mongodb
    entrypoint: /bin/true