version: '2'
services:
  nginx:
    build: ./nginx
    links:
     - web   
    ports:
     - "80:80"
     - "443:443"
  web:
    build: .
    ports:
     - "1313:1313"
    environment:
     - NODE_ENV=production
    links:
     - mongo
  mongo:
    image: mongo
    volumes:
     - /data/mongodb/db:/data/db
    ports:
     - "27017:27017"
