version: '2'
services:
  nginx-service:
    image: jwilder/nginx-proxy
    container_name: nginx-server
    ports:
     - "443:443"
     - "80:80"
    volumes:
      - ./ssl_certs:/etc/nginx/
    environment:
      - VIRTUAL_PORT=1313
  web:
    restart: always
    build:
     context: .
     dockerfile: Dockerfile
    container_name: timesheetapp
    environment:
     - NODE_ENV=production
     - DB_1_PORT_27017_TCP_ADDR=db
     - VIRTUAL_HOST=service.myserver.com
     - VIRTUAL_PROTO=http
    depends_on:
     - db
    ports:
     - "1313:1313"
  db:
    image: mongo:3.2
    ports:
     - "27017:27017"
    restart: always
    volumes_from:
      - db-data
  db-data:
    image: mongo:3.2
    volumes:
      - /data/db
      - /var/lib/mongodb
      - /var/log/mongodb
    entrypoint: /bin/true