############################################################
# Dockerfile to build Nginx Installed Containers
# Based on Ubuntu
############################################################

# Set the base image to Ubuntu
FROM ubuntu:xenial
MAINTAINER BINURA.G

# Install Nginx

# Update the repository
RUN apt-get update -q  \
 && apt-get install -yqq \

# Install necessary tools
RUN apt-get install -y nano wget dialog net-tools

# Download and Install Nginx
RUN apt-get install -y nginx  

# Overwrite the default file with the reverse proxy server settings
COPY default /etc/nginx/sites-available

# OpenSSL certs copy
COPY nginx.key /etc/nginx/ssl
COPY nginx.crt /etc/nginx/ssl

# Append "daemon off;" to the beginning of the configuration
#RUN echo "daemon off;" >> /etc/nginx/nginx.conf

# Expose ports
EXPOSE 80 443

# Set the default command to execute
# when creating a new container
CMD service nginx start