version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes: - ./nginx-configs:/etc/nginx/conf.d
    ports: - "80:80"
  web:
    restart: always
    build:
     context: .
     dockerfile: Dockerfile
    container_name: timesheetapp
    ports:
     - "1313:1313"
    environment:
     - NODE_ENV=production
     - DB_1_PORT_27017_TCP_ADDR=db
    depends_on:
     - db
  db:
    image: mongo:3.2
    ports:
     - "27017:27017"
    restart: always
    volumes_from:
      - db-data
  db-data:
    image: mongo:3.2
    volumes:
      - /data/db
      - /var/lib/mongodb
      - /var/log/mongodb
    entrypoint: /bin/true