############################################################
# Dockerfile to build Nginx Installed Containers
# Based on Ubuntu
############################################################

# Set the base image to Ubuntu
FROM ubuntu:xenial
MAINTAINER BINURA.G

# Install Nginx

# Install Utilities
RUN apt-get update -q && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN apt-get install nginx -y

# Overwrite the default file with the reverse proxy server settings
ADD default /etc/nginx/sites-available

# OpenSSL certs copy
ADD nginx.key /etc/nginx/ssl
ADD nginx.crt /etc/nginx/ssl

# Append "daemon off;" to the beginning of the configuration
#RUN echo "daemon off;" >> /etc/nginx/nginx.conf

# Expose ports
EXPOSE 80 443

# Set the default command to execute
# when creating a new container
CMD service nginx start

#CMD ["nginx", "-g", "daemon off;"]